### ISSUE TITLE
Need a command to list a streams available audio and subtitle options

### ISSUE THREAD

**Issue by StephanieSunshine** [crunchy-labs/crunchy-cli#127]
**Describe the bug**
I have been noticing a pattern where I can't seem to get make crunchy-cli download a stream due to a misconfiguration with the audio or subtitle options.  The most recent example of this is Gurren Lagann where I'm trying to pull my usual Japanese audio with English subtitles and I cannot come up with a working configuration.  If you check out the url itself you'll find Japanese audio with English subtitles are available.

I feel if there was some command to be able to see the available audio and subtitle options it would make it a lot easier to debug and resolve the situation.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy  download -s en-US "https://www.crunchyroll.com/watch/GR751WEKY/bust-through-the-heavens-with-your-drill"
```

**Expected behavior**
Download the respected ts file to the local directory.

**Screenshots**
```
user@computer ➜ ~/bin/crunchy download -s en-US "https://www.crunchyroll.com/watch/GR751WEKY/bust-through-the-heavens-with-your-drill" 
:: ✔ Logging in
:: ✔ Parsed url 1 
:: → Fetching series details
:: • Episode 1 (Bust Through the Heavens With Your Drill) of season 1 (Gurren Lagann) of Gurren Lagann has no en-US subtitles
:: ✔ Skipping url 1 (no matching episodes found)
user@computer ➜ ~/bin/crunchy -v download -s en-US "https://www.crunchyroll.com/watch/GR751WEKY/bust-through-the-heavens-with-your-drill"
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core (1) cli input: Cli { verbosity: Some(Verbosity { v: true, vv: false, q: false }), lang: None, login_method: LoginMethod { credentials: None, etp_rt: None, anonymous: false }, command: Download(Download { audio: en_US, subtitle: Some(en_US), output: "{title}.ts", resolution: Resolution { width: 18446744073709551615, height: 18446744073709551615 }, ffmpeg_preset: [], urls: ["https://www.crunchyroll.com/watch/GR751WEKY/bust-through-the-heavens-with-your-drill"] }) }
[2023-01-30 03:34:52] INFO  crunchy_cli (1) Logging in
[2023-01-30 03:34:52] INFO  crunchy_cli_end (1) 
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core (1) Created context
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core (1) Created ctrl-c handler
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core::cli::download (1) FFmpeg detected
[2023-01-30 03:34:52] INFO  crunchy_cli (1) Parsing url 1
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core::utils::parse (1) Url may contain filters
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core::utils::parse (1) Url filter: UrlFilter { inner: [InnerUrlFilter { from_episode: None, to_episode: None, from_season: None, to_season: None }] }
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core::utils::parse (1) Url type: EpisodeOrMovie("GR751WEKY")
[2023-01-30 03:34:52] INFO  crunchy_cli_core::cli::download (1) Parsed url 1
[2023-01-30 03:34:52] INFO  crunchy_cli_end (1) 
[2023-01-30 03:34:52] INFO  crunchy_cli (1) Fetching series details
[2023-01-30 03:34:52] DEBUG  crunchy_cli_core::cli::download (1) Url 1 is episode 1 (Bust Through the Heavens With Your Drill) of season 1 (Gurren Lagann) of Gurren Lagann
[2023-01-30 03:34:52] ERROR  crunchy_cli_core::cli::download (1) Episode 1 (Bust Through the Heavens With Your Drill) of season 1 (Gurren Lagann) of Gurren Lagann has no en-US subtitles
[2023-01-30 03:34:52] INFO  crunchy_cli_core::cli::download (1) Skipping url 1 (no matching episodes found)
[2023-01-30 03:34:52] INFO  crunchy_cli_end (1) 
user@computer ➜
```

**Client (please complete the following information):**
 - OS: [e.g. Ubuntu Linux]
 - Version [e.g. v3.0.0-dev.4 (4f107d8 2022-12-18)]

**Additional context**

**Comment by ByteDream** [comment]
This is what a potential search command would do too (#20).

**Comment by StephanieSunshine** [comment]
Just as a note if anyone else reads this, I managed before #20 was selected to use the latest `yt-dlp` command with `--list-subs` to actually get a printed list of subs. I believe ( I saw this with Your Name ) that if Crunchyroll only has one audio track and one subtitle track, that it hard encodes the sub.  I verified this with Your Name, as playing it in the browsers wouldn't let me turn the subs off. I just checked Gurren Lagann using the `yt-dlp` subs lookup and it looks like it is the exact same way ( hard coded audio and subs, `yt-dlp` reports no subtitles available ). The way I've been able to figure out if they are hard coded is to go into the browser and try and turn the subs off. If you can't turn them off, then it seems because it is hard coded.

I just tried to pull Gurren Lagann using the `crunchy-cli 3.0.0-dev.8 (a6bfe0b 2023-03-09)` build without an audio or subtitle flag and I keep getting a crash that is probably related to something else. Using `yt-dlp` to pull Gurren Lagann ended up with hard coded subs and Japanese audio. Playback worked as expected.

For completeness, below is the error I'm seeing from `crunchy-cli`

```shell
stephanie@agartha ➜ RUST_BACKTRACE=1 ~/bin/crunchy-cli download -o "S{season_number}E{episode_number}_{title}.ts" https://www.crunchyroll.com/watch/GR751WEKY/bust-through-the-heavens-with-your-drill
:: ✔ Logging in
:: ✔ Parsed url 1
:: \ Fetching series details                                                    
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/stephanie/.cargo/registry/src/github.com-1ecc6299db9ec823/crunchyroll-rs-0.2.5/src/media/streaming.rs:141:1
stack backtrace:
:: | Fetching series details                                                    
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stephanie@agartha ➜ RUST_BACKTRACE=full ~/bin/crunchy-cli download -o "S{season_number}E{episode_number}_{title}.ts" https://www.crunchyroll.com/watch/GR751WEKY/bust-through-the-heavens-with-your-drill
:: ✔ Logging in
:: ✔ Parsed url 1
:: \ Fetching series details                                                    
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/stephanie/.cargo/registry/src/github.com-1ecc6299db9ec823/crunchyroll-rs-0.2.5/src/media/streaming.rs:141:1
stack backtrace:
   0:     0x55ec3cb29896 - <unknown>
   1:     0x55ec3c911a6c - <unknown>
   2:     0x55ec3cb13964 - <unknown>
   3:     0x55ec3cb176a4 - <unknown>
   4:     0x55ec3cb181f2 - <unknown>
   5:     0x55ec3cb29cdb - <unknown>
   6:     0x55ec3cb29c76 - <unknown>
   7:     0x55ec3cb17bb0 - <unknown>
   8:     0x55ec3c8b4c52 - <unknown>
   9:     0x55ec3c8b4cac - <unknown>
  10:     0x55ec3c99062e - <unknown>
  11:     0x55ec3c9900cc - <unknown>
  12:     0x55ec3c99ff97 - <unknown>
  13:     0x55ec3c99b2c6 - <unknown>
  14:     0x55ec3c9996a1 - <unknown>
  15:     0x55ec3c8bdd47 - <unknown>
  16:     0x55ec3c8c3952 - <unknown>
  17:     0x55ec3c91b153 - <unknown>
  18:     0x55ec3c91d523 - <unknown>
  19:     0x55ec3c919dee - <unknown>
  20:     0x7fb194629d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21:     0x7fb194629e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  22:     0x55ec3c8ba455 - <unknown>
  23:                0x0 - <unknown>
```
